### ISSUE TITLE
XDK Support?

### ISSUE THREAD

**Issue by lllsondowlll** [silent06/stealth-Server-3.0#3]
This says it supports Xbox Development Kits, but there is no information on the Shadowboot that is being used, nor the patch addresses for us to create our own. RGLoader spoofed to 17559 shadowbooted on a devkit doesn't seem to work with stealth.xex as nothing changes. Please advise.

**Comment by silent06** [comment]
You have to use memory fixer first before you can go online or use any xex images. Connect it through xbox neighborhood 1st. When I flashed my rgloader a few years ago none of the online tutorials mentioned this. I dont have an actual devkit but I had a friend test out the code & was able to go online. Im sure what the setup is for that since I dont have one. But the code for rgLoader & devkit is the same. 


XDK source code
https://www.mediafire.com/file/9ntbw2f9083tebt/linux.zip/file

Code needed to go convert any stealth source from 17559 to 17489 for RGloader/xdk to go online
https://justpaste.it/dfbpn

More sources-
XbLive(lots of XDK code, colors, UI etc)- https://1fichier.com/?3orob25ny0iayd7naqbc
TheByte- https://1fichier.com/?xhdtqnhtt4n7xoix7e8k

Stealth Source Folder-
https://1fichier.com/dir/cyTAh2nD

**Comment by lllsondowlll** [comment]
> You have to use memory fixer first before you can go online or use any xex images. Connect it through xbox neighborhood 1st. When I flashed my rgloader a few years ago none of the online tutorials mentioned this. I dont have an actual devkit but I had a friend test out the code & was able to go online. Im sure what the setup is for that since I dont have one. But the code for rgLoader & devkit is the same.
> 
> XDK source code https://www.mediafire.com/file/9ntbw2f9083tebt/linux.zip/file
> 
> Code needed to go convert any stealth source from 17559 to 17489 for RGloader/xdk to go online https://justpaste.it/dfbpn
> 
> More sources- XbLive(lots of XDK code, colors, UI etc)- https://1fichier.com/?3orob25ny0iayd7naqbc TheByte- https://1fichier.com/?xhdtqnhtt4n7xoix7e8k
> 
> Stealth Source Folder- https://1fichier.com/dir/cyTAh2nD

With an actual devkit with rgloader shadowboot you don't need to use memory fixer. Using the sources you provided I discovered that there is an isDevkit check in globals which looks if the stealth binary is devkit signed. Since rgloader shadowboot can run retail xex's this is why the console was crashing / bootlooping as by default you serve up a retail signed xex and the devkit was loading it anyway with the retail memory space. 

Please update instructions to include signing as devkit for devkits, and then you can close this issue out as I tested devkit signing on the binary you provided and verified it's working.

**Comment by lllsondowlll** [comment]
I'll just self close it as I plan on forking this repo anyway to pair with my RGloader 17559 branch. I can push readme upstream at a later date.
